/**
 * Central Dataset and Variable Registry (Frontend Authoritative Definitions)
 *
 * Synchronized with the backend authoritative registry.
 * Delineates Products vs. Datasets, enforces variable compatibility,
 * and maintains official Copernicus Marine, Argo GDAC, GLORYS, and INCOIS identities.
 */

import type { CanonicalVariable, RegisteredDataset } from '../types/unifiedData';

export const CANONICAL_VARIABLES: Record<string, CanonicalVariable> = {
  thetao: {
    id: 'thetao',
    display_name: 'Potential Temperature (thetao)',
    cf_standard_name: 'sea_water_potential_temperature',
    unit: '°C',
    category: 'thermodynamic',
    description: 'Sea water potential temperature referenced to sea surface pressure.',
    valid_range: [-2.0, 38.0],
    is_derived: false,
    aliases: ['temperature', 'TEMP', 'temp'],
  },
  temperature: {
    id: 'temperature',
    display_name: 'In-Situ / Potential Temperature',
    cf_standard_name: 'sea_water_temperature',
    unit: '°C',
    category: 'thermodynamic',
    description: 'Observed in-situ temperature or model potential temperature.',
    valid_range: [-2.0, 38.0],
    is_derived: false,
    aliases: ['thetao', 'TEMP', 'temp'],
  },
  so: {
    id: 'so',
    display_name: 'Practical Salinity (so)',
    cf_standard_name: 'sea_water_salinity',
    unit: 'PSU',
    category: 'thermodynamic',
    description: 'Practical salinity on the Practical Salinity Scale 1978.',
    valid_range: [0.0, 44.0],
    is_derived: false,
    aliases: ['salinity', 'PSAL', 'saln', 'SALN'],
  },
  salinity: {
    id: 'salinity',
    display_name: 'Practical Salinity',
    cf_standard_name: 'sea_water_salinity',
    unit: 'PSU',
    category: 'thermodynamic',
    description: 'Observed or model practical salinity.',
    valid_range: [0.0, 44.0],
    is_derived: false,
    aliases: ['so', 'PSAL', 'saln', 'SALN'],
  },
  pressure: {
    id: 'pressure',
    display_name: 'Pressure',
    cf_standard_name: 'sea_water_pressure',
    unit: 'dbar',
    category: 'coordinate',
    description: 'Hydrostatic pressure vertical coordinate.',
    valid_range: [0.0, 6000.0],
    is_derived: false,
    aliases: ['PRES', 'pres', 'depth'],
  },
  uo: {
    id: 'uo',
    display_name: 'Eastward Current Velocity (uo)',
    cf_standard_name: 'eastward_sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Zonal (eastward) ocean current velocity component.',
    valid_range: [-5.0, 5.0],
    is_derived: false,
    aliases: ['currents_u', 'UVEL', 'u'],
  },
  currents_u: {
    id: 'currents_u',
    display_name: 'Eastward Current Velocity (u)',
    cf_standard_name: 'eastward_sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Eastward sea water velocity component.',
    valid_range: [-5.0, 5.0],
    is_derived: false,
    aliases: ['uo', 'UVEL', 'u'],
  },
  vo: {
    id: 'vo',
    display_name: 'Northward Current Velocity (vo)',
    cf_standard_name: 'northward_sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Meridional (northward) ocean current velocity component.',
    valid_range: [-5.0, 5.0],
    is_derived: false,
    aliases: ['currents_v', 'VVEL', 'v'],
  },
  currents_v: {
    id: 'currents_v',
    display_name: 'Northward Current Velocity (v)',
    cf_standard_name: 'northward_sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Northward sea water velocity component.',
    valid_range: [-5.0, 5.0],
    is_derived: false,
    aliases: ['vo', 'VVEL', 'v'],
  },
  wo: {
    id: 'wo',
    display_name: 'Upward Velocity (wo)',
    cf_standard_name: 'upward_sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Vertical ocean velocity component (positive upward).',
    valid_range: [-0.1, 0.1],
    is_derived: false,
    aliases: ['w', 'wcur'],
  },
  zos: {
    id: 'zos',
    display_name: 'Sea Surface Height (zos)',
    cf_standard_name: 'sea_surface_height_above_geoid',
    unit: 'm',
    category: 'dynamic',
    description: 'Sea surface height above geoid.',
    valid_range: [-3.0, 3.0],
    is_derived: false,
    aliases: ['ssh'],
  },
  mlotst: {
    id: 'mlotst',
    display_name: 'Mixed Layer Thickness (mlotst)',
    cf_standard_name: 'ocean_mixed_layer_thickness_defined_by_sigma_theta',
    unit: 'm',
    category: 'thermodynamic',
    description: 'Ocean mixed layer thickness defined by density threshold.',
    valid_range: [0.0, 1000.0],
    is_derived: false,
    aliases: ['mld'],
  },
  current_speed: {
    id: 'current_speed',
    display_name: 'Current Speed (Derived)',
    cf_standard_name: 'sea_water_speed',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Derived current magnitude: sqrt(uo^2 + vo^2). Computed only when uo and vo are retrieved.',
    valid_range: [0.0, 7.0],
    is_derived: true,
    derived_expression: 'sqrt(uo^2 + vo^2)',
    aliases: ['speed', 'magnitude'],
  },
  current_direction: {
    id: 'current_direction',
    display_name: 'Current Direction (Derived)',
    cf_standard_name: 'sea_water_velocity_to_direction',
    unit: 'degrees',
    category: 'dynamic',
    description: 'Derived current flow direction in degrees clockwise from true north: (atan2(uo, vo) * 180 / pi) % 360.',
    valid_range: [0.0, 360.0],
    is_derived: true,
    derived_expression: '(atan2(uo, vo) * 180 / pi) % 360',
    aliases: ['direction', 'current_dir', 'heading'],
  },
  currents: {
    id: 'currents',
    display_name: 'Ocean Horizontal Currents (Velocity & Flow)',
    cf_standard_name: 'sea_water_velocity',
    unit: 'm/s',
    category: 'dynamic',
    description: 'Unified ocean horizontal current vectors combining eastward (uo) and northward (vo) velocity components with derived speed magnitude and flow heading.',
    valid_range: [0.0, 7.0],
    is_derived: true,
    derived_expression: 'speed = sqrt(uo^2 + vo^2), direction = (atan2(uo, vo) * 180 / pi) % 360',
    aliases: ['current', 'velocity', 'flow', 'CURR', 'uv', 'ocean_currents'],
  },
  chlorophyll: {
    id: 'chlorophyll',
    display_name: 'Chlorophyll-a',
    cf_standard_name: 'mass_concentration_of_chlorophyll_a_in_sea_water',
    unit: 'mg/m³',
    category: 'biogeochemical',
    description: 'Chlorophyll-a mass concentration in sea water (Biogeochemical product).',
    valid_range: [0.0, 50.0],
    is_derived: false,
    aliases: ['chl', 'CHL'],
  },
  chl: {
    id: 'chl',
    display_name: 'Chlorophyll-a (chl)',
    cf_standard_name: 'mass_concentration_of_chlorophyll_a_in_sea_water',
    unit: 'mg/m³',
    category: 'biogeochemical',
    description: 'Chlorophyll-a mass concentration in sea water.',
    valid_range: [0.0, 50.0],
    is_derived: false,
    aliases: ['chlorophyll', 'CHL'],
  },
  o2: {
    id: 'o2',
    display_name: 'Dissolved Oxygen (o2)',
    cf_standard_name: 'mole_concentration_of_dissolved_molecular_oxygen_in_sea_water',
    unit: 'mmol/m³',
    category: 'biogeochemical',
    description: 'Dissolved oxygen concentration in sea water.',
    valid_range: [0.0, 500.0],
    is_derived: false,
    aliases: ['oxygen', 'dissolved_oxygen'],
  },
  dissolved_oxygen: {
    id: 'dissolved_oxygen',
    display_name: 'Dissolved Oxygen Concentration',
    cf_standard_name: 'mole_concentration_of_dissolved_molecular_oxygen_in_sea_water',
    unit: 'mmol/m³',
    category: 'biogeochemical',
    description: 'Dissolved oxygen concentration in sea water.',
    valid_range: [0.0, 500.0],
    is_derived: false,
    aliases: ['o2', 'oxygen'],
  },
  no3: {
    id: 'no3',
    display_name: 'Nitrate Concentration (no3)',
    cf_standard_name: 'mole_concentration_of_nitrate_in_sea_water',
    unit: 'mmol/m³',
    category: 'biogeochemical',
    description: 'Nitrate concentration in sea water.',
    valid_range: [0.0, 100.0],
    is_derived: false,
    aliases: ['nitrate'],
  },
  nitrate: {
    id: 'nitrate',
    display_name: 'Nitrate Concentration',
    cf_standard_name: 'mole_concentration_of_nitrate_in_sea_water',
    unit: 'mmol/m³',
    category: 'biogeochemical',
    description: 'Nitrate concentration in sea water.',
    valid_range: [0.0, 100.0],
    is_derived: false,
    aliases: ['no3'],
  },
};

export const REGISTERED_DATASETS: RegisteredDataset[] = [
  // ── 1. GLORYS12V1 × Argo Collocation ─────────────────────────────────────────
  {
    dataset_id: 'glorys12v1-argo-collocation-bob',
    dataset_name: 'GLORYS12V1 × Argo Delayed Mode Collocation (Bay of Bengal)',
    product_id: 'cmems_mod_glo_phy_my_0.083deg_P1D-m',
    product_name: 'Global Ocean Physics Reanalysis GLORYS12V1',
    source_id: 'glorys12v1',
    source_name: 'Mercator Ocean / Copernicus Marine',
    source_type: 'collocation',
    description: 'Precomputed scientific collocation pairs comparing GLORYS12V1 reanalysis with in-situ Argo Delayed Mode profiles in the Bay of Bengal (Jan 1–14, 2024, 0–500 dbar). Difference convention: GLORYS - Argo.',
    supported_variables: ['temperature', 'salinity', 'thetao', 'so', 'pressure'],
    variable_units: { temperature: '°C', salinity: 'PSU', thetao: '°C', so: 'PSU', pressure: 'dbar' },
    spatial_coverage: { south: 7.80, north: 15.52, west: 83.47, east: 90.26, region_name: 'Bay of Bengal' },
    temporal_coverage: {
      start: '2024-01-01',
      end: '2024-01-14',
      resolution: 'event-based',
      available_dates: [
        '2024-01-01', '2024-01-04', '2024-01-06', '2024-01-07',
        '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-11',
        '2024-01-14',
      ],
    },
    vertical_coverage: { min_depth: 0.5, max_depth: 500.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'Scientific Collocation Benchmark',
    quality_control_applied: true,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    qc_details: 'Argo Delayed Mode QC applied; GLORYS collocated in space, depth, and time.',
    citation: 'GLORYS12V1 Reanalysis / Argo Delayed Mode. CMEMS & GDAC.',
  },

  // ── 2. Argo Delayed Mode In-Situ Observations ────────────────────────────────
  {
    dataset_id: 'argo-delayed-mode-bob-2024',
    dataset_name: 'Argo Delayed Mode Profiles (Bay of Bengal Jan 2024)',
    product_id: 'argo_global_delayed_mode',
    product_name: 'Argo Global Data Assembly Centre Delayed Mode',
    source_id: 'argo-gdac',
    source_name: 'Argo Global Data Assembly Centre (GDAC)',
    source_type: 'observation',
    description: 'Official Argo Delayed Mode vertical CTD profiles in the Bay of Bengal from Jan 1–14, 2024 with verified quality control flags.',
    supported_variables: ['temperature', 'salinity', 'pressure'],
    variable_units: { temperature: '°C', salinity: 'PSU', pressure: 'dbar' },
    spatial_coverage: { south: 7.80, north: 15.52, west: 83.47, east: 90.26, region_name: 'Bay of Bengal' },
    temporal_coverage: {
      start: '2024-01-01',
      end: '2024-01-14',
      resolution: 'event-based',
      available_dates: [
        '2024-01-01', '2024-01-04', '2024-01-06', '2024-01-07',
        '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-11',
        '2024-01-14',
      ],
    },
    vertical_coverage: { min_depth: 0.0, max_depth: 500.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'L3 Delayed Mode In-Situ',
    quality_control_applied: true,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    qc_details: 'PRES_QC, TEMP_QC, PSAL_QC flags 1 (good) and 2 (probably good) validated.',
    citation: 'Argo (2024). Argo float data and metadata from Global Data Assembly Centre. Ifremer.',
  },

  // ── 3. Argo GDAC Latest Available Synthetic Stream ───────────────────────────
  {
    dataset_id: 'argo-gdac-latest-synthetic',
    dataset_name: 'Argo GDAC Latest Synthetic Profiles (On-Demand Upstream)',
    product_id: 'argo_synthetic_profile_index',
    product_name: 'Argo Global Real-Time & Adjusted In-Situ Stream',
    source_id: 'argo-gdac',
    source_name: 'Argo Global Data Assembly Centre (GDAC)',
    source_type: 'observation',
    description: 'On-demand live querying of official Argo GDAC synthetic profile index and direct profile NetCDF fetching with strict QC 1/2 filtering.',
    supported_variables: ['temperature', 'salinity', 'pressure'],
    variable_units: { temperature: '°C', salinity: 'PSU', pressure: 'dbar' },
    spatial_coverage: { south: 5.0, north: 22.0, west: 80.0, east: 95.0, region_name: 'Bay of Bengal' },
    temporal_coverage: { start: 'dynamic_last_90_days', end: 'present', resolution: 'event-based' },
    vertical_coverage: { min_depth: 0.0, max_depth: 500.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'gdac_index',
    processing_level: 'L2 Real-Time / L3 Adjusted In-Situ',
    quality_control_applied: true,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    qc_details: 'Per-level PRES/TEMP/PSAL QC 1/2 enforced. Raw/Adjusted data mode respected.',
    documentation_url: 'https://data-argo.ifremer.fr',
    citation: 'Argo GDAC real-time synthetic profile stream.',
  },

  // ── 4. INCOIS HYCOM Operational Regional Model ──────────────────────────────
  {
    dataset_id: 'incois-hycom-2.35-operational',
    dataset_name: 'INCOIS Regional HYCOM 2.35 Operational Forecast',
    product_id: 'incois_hycom_regional',
    product_name: 'INCOIS Indian Ocean Regional HYCOM',
    source_id: 'incois-hycom',
    source_name: 'Indian National Centre for Ocean Information Services (INCOIS)',
    source_type: 'model',
    description: 'Operational regional HYCOM model output for Indian Ocean / Bay of Bengal covering Aug 26 – Sep 01, 2026 at 6-hourly intervals on standard depth levels (0, 17.5, 52.5, 125, 275, 500 m). Separate from Research Mode.',
    supported_variables: ['temperature', 'salinity', 'currents_u', 'currents_v', 'uo', 'vo', 'current_speed', 'current_direction'],
    variable_units: { temperature: '°C', salinity: 'PSU', currents_u: 'm/s', currents_v: 'm/s', uo: 'm/s', vo: 'm/s', current_speed: 'm/s', current_direction: 'degrees' },
    spatial_coverage: { south: 5.063, north: 21.943, west: 78.02, east: 99.86, region_name: 'North Indian Ocean / BOB' },
    temporal_coverage: { start: '2026-08-26T06:00:00Z', end: '2026-09-01T00:00:00Z', resolution: '6-hourly' },
    vertical_coverage: {
      min_depth: 0.0,
      max_depth: 500.0,
      unit: 'm',
      standard_levels: [0.0, 17.5, 52.5, 125.0, 275.0, 500.0],
    },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'Operational Regional Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    citation: 'INCOIS HYCOM operational run RSMC_hycom_20260827.nc',
  },

  // ── 5. Copernicus Global Ocean Physics Analysis & Forecast ───────────────────
  {
    dataset_id: 'cmems_mod_glo_phy-thetao_anfc_0.083deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Physics Potential Temperature (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D potential temperature (thetao) on 1/12° grid (approx 8km) from NEMO ocean model.',
    supported_variables: ['thetao', 'temperature'],
    variable_units: { thetao: '°C', temperature: '°C' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-thetao_anfc_0.083deg_PT6H-i',
    dataset_name: 'Copernicus Global Ocean Physics Potential Temperature (6-Hourly Instantaneous)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official 6-hourly instantaneous 3D potential temperature (thetao) on 1/12° grid.',
    supported_variables: ['thetao', 'temperature'],
    variable_units: { thetao: '°C', temperature: '°C' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'PT6H-i' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-so_anfc_0.083deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Physics Salinity (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D practical salinity (so) on 1/12° grid from NEMO ocean model.',
    supported_variables: ['so', 'salinity'],
    variable_units: { so: 'PSU', salinity: 'PSU' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-so_anfc_0.083deg_PT6H-i',
    dataset_name: 'Copernicus Global Ocean Physics Salinity (6-Hourly Instantaneous)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official 6-hourly instantaneous 3D practical salinity (so) on 1/12° grid.',
    supported_variables: ['so', 'salinity'],
    variable_units: { so: 'PSU', salinity: 'PSU' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'PT6H-i' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-cur_anfc_0.083deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Physics Horizontal Currents (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D horizontal velocity components (uo, vo) on 1/12° grid with derived speed and direction.',
    supported_variables: ['uo', 'vo', 'currents_u', 'currents_v', 'current_speed', 'current_direction'],
    variable_units: { uo: 'm/s', vo: 'm/s', currents_u: 'm/s', currents_v: 'm/s', current_speed: 'm/s', current_direction: 'degrees' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-cur_anfc_0.083deg_PT6H-i',
    dataset_name: 'Copernicus Global Ocean Physics Horizontal Currents (6-Hourly Instantaneous)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official 6-hourly instantaneous 3D horizontal velocity components (uo, vo) on 1/12° grid.',
    supported_variables: ['uo', 'vo', 'currents_u', 'currents_v', 'current_speed', 'current_direction'],
    variable_units: { uo: 'm/s', vo: 'm/s', currents_u: 'm/s', currents_v: 'm/s', current_speed: 'm/s', current_direction: 'degrees' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'PT6H-i' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy-wcur_anfc_0.083deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Physics Upward Velocity (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D vertical ocean velocity (wo) on 1/12° grid.',
    supported_variables: ['wo'],
    variable_units: { wo: 'm/s' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },
  {
    dataset_id: 'cmems_mod_glo_phy_anfc_0.083deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Physics 2D & Surface Fields (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_PHY_001_024',
    product_name: 'Global Ocean Physics Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 2D ocean physics fields including Sea Surface Height (zos) and Mixed Layer Thickness (mlotst) on 1/12° grid.',
    supported_variables: ['zos', 'mlotst'],
    variable_units: { zos: 'm', mlotst: 'm' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.0, max_depth: 0.0, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: false,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-024.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_PHY_001_024',
  },

  // ── Copernicus Global Ocean Biogeochemical Analysis & Forecast ───────────
  {
    dataset_id: 'cmems_mod_glo_bgc-pft_anfc_0.25deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Biogeochemistry Plankton & Chlorophyll (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_BGC_001_028',
    product_name: 'Global Ocean Biogeochemistry Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D chlorophyll-a mass concentration (chl) and phytoplankton carbon (phyc) on 1/4° grid from PISCES biogeochemical model.',
    supported_variables: ['chl', 'chlorophyll'],
    variable_units: { chl: 'mg/m³', chlorophyll: 'mg/m³' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Biogeochemical Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-028.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_BGC_001_028',
  },
  {
    dataset_id: 'cmems_mod_glo_bgc-bio_anfc_0.25deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Biogeochemistry Dissolved Oxygen & Production (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_BGC_001_028',
    product_name: 'Global Ocean Biogeochemistry Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D dissolved molecular oxygen (o2) and net primary production (nppv) on 1/4° grid from PISCES model.',
    supported_variables: ['o2', 'dissolved_oxygen'],
    variable_units: { o2: 'mmol/m³', dissolved_oxygen: 'mmol/m³' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Biogeochemical Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-028.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_BGC_001_028',
  },
  {
    dataset_id: 'cmems_mod_glo_bgc-nut_anfc_0.25deg_P1D-m',
    dataset_name: 'Copernicus Global Ocean Biogeochemistry Nutrients / Nitrate (Daily Mean)',
    product_id: 'GLOBAL_ANALYSISFORECAST_BGC_001_028',
    product_name: 'Global Ocean Biogeochemistry Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'model',
    description: 'Official daily mean 3D nitrate (no3), phosphate (po4), silicate (si), and iron (fe) on 1/4° grid from PISCES model.',
    supported_variables: ['no3', 'nitrate'],
    variable_units: { no3: 'mmol/m³', nitrate: 'mmol/m³' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-11-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.5, max_depth: 5727.9, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Biogeochemical Analysis/Forecast',
    quality_control_applied: false,
    supports_3d: true,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-GLO-PUM-001-028.pdf',
    citation: 'E.U. Copernicus Marine Service Information: GLOBAL_ANALYSISFORECAST_BGC_001_028',
  },
  // ── 6. Copernicus Global Ocean Colour NRT Satellite Chlorophyll (Surface-Only) ──
  {
    dataset_id: 'cmems_obs-oc_glo_bgc-plankton_nrt_l4-gapfree-multi-4km_P1D',
    dataset_name: 'Copernicus Global Ocean Colour Satellite Surface Chlorophyll-a (Daily 4km L4)',
    product_id: 'OCEANCOLOUR_GLO_BGC_L4_NRT_009_102',
    product_name: 'Global Ocean Colour Analysis and Forecast',
    source_id: 'copernicus-marine',
    source_name: 'Copernicus Marine Service (CMEMS)',
    source_type: 'observation',
    description: 'Daily gap-free multi-sensor satellite observation of surface Chlorophyll-a mass concentration (CHL) on 4km grid. Surface-only product (depth = 0 m).',
    supported_variables: ['chl', 'chlorophyll'],
    variable_units: { chl: 'mg/m³', chlorophyll: 'mg/m³' },
    spatial_coverage: { south: -80.0, north: 90.0, west: -180.0, east: 180.0, region_name: 'Global' },
    temporal_coverage: { start: '2021-01-01', end: 'present', resolution: 'P1D-m' },
    vertical_coverage: { min_depth: 0.0, max_depth: 0.0, unit: 'm' },
    availability_status: 'available',
    retrieval_capability: 'live_api',
    processing_level: 'L4 Satellite Observation (Surface-Only)',
    quality_control_applied: true,
    data_mode: 'LIVE_NRT',
    platform_type: 'BGC',
    vertical_coverage_type: 'surface_only',
    supports_3d: false,
    supports_surface: true,
    supports_subset: true,
    credential_requirement: 'Copernicus Marine Service Account',
    documentation_url: 'https://catalogue.marine.copernicus.eu/documents/PUM/CMEMS-OC-PUM-009-ALL.pdf',
    citation: 'E.U. Copernicus Marine Service: OCEANCOLOUR_GLO_BGC_L4_NRT_009_102',
  },
  // ── 7. Ocean Glider Historical In-Situ Profiles (Bay of Bengal) ──────────────
  {
    dataset_id: 'glider-incois-bob-historical',
    dataset_name: 'Autonomous Ocean Glider CTD/BGC Transects (Bay of Bengal)',
    product_id: 'ocean_gliders_incois_bob',
    product_name: 'OceanGliders International & Regional Network',
    source_id: 'ocean-gliders',
    source_name: 'OceanGliders / INCOIS National Glider Facility',
    source_type: 'observation',
    description: 'High-resolution saw-tooth transects from autonomous ocean gliders measuring temperature, salinity, and bio-optical variables in the Bay of Bengal.',
    supported_variables: ['temperature', 'salinity', 'chl', 'pressure', 'thetao', 'so'],
    variable_units: { temperature: '°C', salinity: 'PSU', chl: 'mg/m³', pressure: 'dbar', thetao: '°C', so: 'PSU' },
    spatial_coverage: { south: 8.0, north: 19.5, west: 82.0, east: 92.5, region_name: 'Bay of Bengal' },
    temporal_coverage: { start: '2023-01-01', end: '2024-12-31', resolution: 'event-based' },
    vertical_coverage: { min_depth: 0.0, max_depth: 1000.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'L2/L3 OceanGlider In-Situ',
    quality_control_applied: true,
    data_mode: 'HISTORICAL_RESEARCH',
    platform_type: 'GLIDER',
    vertical_coverage_type: 'depth_resolved',
    supports_3d: true,
    supports_surface: true,
    qc_details: 'OceanGliders Standard Operating Procedure QC applied.',
    citation: 'OceanGliders (2024). Bay of Bengal glider mission observations.',
  },
  // ── 8. Shipboard CTD Hydrographic Casts (Bay of Bengal Research Cruises) ──────
  {
    dataset_id: 'ctd-cchdo-bob-historical',
    dataset_name: 'Research Cruise Shipboard CTD Casts (Bay of Bengal)',
    product_id: 'cchdo_hydrographic_cruises',
    product_name: 'CLIVAR & Carbon Hydrographic Data Office (CCHDO)',
    source_id: 'cchdo-ctd',
    source_name: 'CCHDO / WOCE Hydrographic Programme',
    source_type: 'observation',
    description: 'High-precision shipboard CTD rosette station profiles collecting depth-resolved temperature, salinity, dissolved oxygen, and nutrients in the Bay of Bengal.',
    supported_variables: ['temperature', 'salinity', 'pressure', 'o2', 'no3', 'chl', 'thetao', 'so'],
    variable_units: { temperature: '°C', salinity: 'PSU', pressure: 'dbar', o2: 'mmol/m³', no3: 'mmol/m³', chl: 'mg/m³', thetao: '°C', so: 'PSU' },
    spatial_coverage: { south: 6.0, north: 21.0, west: 80.0, east: 94.0, region_name: 'Bay of Bengal' },
    temporal_coverage: { start: '2020-01-01', end: '2024-06-30', resolution: 'station-based' },
    vertical_coverage: { min_depth: 0.0, max_depth: 4500.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'WOCE/GO-SHIP Quality Controlled Hydrographic Data',
    quality_control_applied: true,
    data_mode: 'HISTORICAL_RESEARCH',
    platform_type: 'CTD',
    vertical_coverage_type: 'depth_resolved',
    supports_3d: true,
    supports_surface: true,
    qc_details: 'WOCE/GO-SHIP 2: Good, 3: Questionable QC standard applied.',
    citation: 'CCHDO Cruise CTD Observations, Bay of Bengal.',
  },
  // ── 9. Biogeochemical In-Situ Observations (BGC-Argo Profiles) ───────────────
  {
    dataset_id: 'bgc-argo-bob-historical',
    dataset_name: 'BGC-Argo Float Profiles (Bay of Bengal)',
    product_id: 'bgc_argo_global',
    product_name: 'Biogeochemical Argo Global Data Assembly Centre',
    source_id: 'argo-gdac',
    source_name: 'BGC-Argo / Ifremer GDAC',
    source_type: 'observation',
    description: 'In-situ biogeochemical vertical profiles from BGC-Argo profilers measuring chlorophyll-a fluorescence, dissolved oxygen, and nitrate in the Bay of Bengal.',
    supported_variables: ['chl', 'o2', 'no3', 'chlorophyll', 'dissolved_oxygen', 'nitrate', 'temperature', 'salinity', 'pressure'],
    variable_units: { chl: 'mg/m³', o2: 'mmol/m³', no3: 'mmol/m³', chlorophyll: 'mg/m³', dissolved_oxygen: 'mmol/m³', nitrate: 'mmol/m³', temperature: '°C', salinity: 'PSU', pressure: 'dbar' },
    spatial_coverage: { south: 7.0, north: 18.0, west: 82.0, east: 93.0, region_name: 'Bay of Bengal' },
    temporal_coverage: { start: '2023-01-01', end: '2024-12-31', resolution: 'event-based' },
    vertical_coverage: { min_depth: 0.0, max_depth: 1000.0, unit: 'dbar' },
    availability_status: 'available',
    retrieval_capability: 'local_file',
    processing_level: 'L3 Quality Controlled BGC-Argo',
    quality_control_applied: true,
    data_mode: 'HISTORICAL_RESEARCH',
    platform_type: 'BGC',
    vertical_coverage_type: 'depth_resolved',
    supports_3d: true,
    supports_surface: true,
    qc_details: 'BGC-Argo QF 1/2 validated.',
    citation: 'BGC-Argo Global Data Assembly Centre (2024).',
  },
];

export const CANONICAL_PLATFORMS = {
  ARGO: {
    platform_type: 'ARGO',
    display_name: 'Argo Profiling Floats',
    description: 'Autonomous profiling floats measuring temperature and salinity from surface to 2000 dbar.',
    data_modes_supported: ['LIVE_NRT', 'HISTORICAL_RESEARCH'],
    typical_variables: ['temperature', 'salinity', 'pressure'],
    typical_vertical_range: [0.0, 2000.0],
    vertical_coverage_type: 'depth_resolved',
    badgeColor: 'bg-emerald-950 text-emerald-300 border-emerald-800/60',
  },
  GLIDER: {
    platform_type: 'GLIDER',
    display_name: 'Ocean Autonomous Gliders',
    description: 'Autonomous underwater gliders performing high-resolution saw-tooth transects.',
    data_modes_supported: ['HISTORICAL_RESEARCH'],
    typical_variables: ['temperature', 'salinity', 'chl', 'pressure'],
    typical_vertical_range: [0.0, 1000.0],
    vertical_coverage_type: 'depth_resolved',
    badgeColor: 'bg-amber-950 text-amber-300 border-amber-800/60',
  },
  CTD: {
    platform_type: 'CTD',
    display_name: 'Shipboard CTD Casts',
    description: 'High-precision shipboard CTD rosette station profiles collecting full-depth hydrography.',
    data_modes_supported: ['HISTORICAL_RESEARCH'],
    typical_variables: ['temperature', 'salinity', 'pressure', 'o2', 'chl', 'no3'],
    typical_vertical_range: [0.0, 6000.0],
    vertical_coverage_type: 'depth_resolved',
    badgeColor: 'bg-blue-950 text-blue-300 border-blue-800/60',
  },
  BGC: {
    platform_type: 'BGC',
    display_name: 'Biogeochemical Observations',
    description: 'Biogeochemical sensors measuring chlorophyll-a, dissolved oxygen, and nitrate.',
    data_modes_supported: ['LIVE_NRT', 'HISTORICAL_RESEARCH'],
    typical_variables: ['chl', 'o2', 'no3'],
    typical_vertical_range: [0.0, 2000.0],
    vertical_coverage_type: 'depth_resolved',
    badgeColor: 'bg-teal-950 text-teal-300 border-teal-800/60',
  },
};

export const CANONICAL_DATA_MODES = {
  LIVE_NRT: {
    mode: 'LIVE_NRT',
    display_name: 'Live / Near-Real-Time (NRT)',
    description: 'Upstream operational streams, recent Argo GDAC profilers, and Copernicus operational forecasts.',
    badgeColor: 'bg-teal-950 text-teal-300 border-teal-800/60',
  },
  HISTORICAL_RESEARCH: {
    mode: 'HISTORICAL_RESEARCH',
    display_name: 'Research / Historical Benchmark',
    description: 'Verified delayed-mode observations, GLORYS12V1 ocean reanalysis collocations, and peer-reviewed benchmarks.',
    badgeColor: 'bg-cyan-950 text-cyan-300 border-cyan-800/60',
  },
};

export const SOURCE_PROVIDERS = [
  { id: 'glorys12v1', name: 'GLORYS12V1 Reanalysis (CMEMS)', type: 'reanalysis' },
  { id: 'argo-gdac', name: 'Argo Global Data Assembly Centre (GDAC)', type: 'observation' },
  { id: 'ocean-gliders', name: 'OceanGliders International Network', type: 'observation' },
  { id: 'cchdo-ctd', name: 'CCHDO / WOCE Hydrographic Programme', type: 'observation' },
  { id: 'incois-hycom', name: 'INCOIS HYCOM Operational', type: 'model' },
  { id: 'copernicus-marine', name: 'Copernicus Marine Service (CMEMS)', type: 'model' },
];

export function getDatasetsBySource(sourceId: string): RegisteredDataset[] {
  return REGISTERED_DATASETS.filter((d) => d.source_id === sourceId);
}

export function getDatasetById(datasetId: string): RegisteredDataset | undefined {
  return REGISTERED_DATASETS.find((d) => d.dataset_id === datasetId);
}

export function getSupportedVariablesForDataset(datasetId: string): CanonicalVariable[] {
  const ds = getDatasetById(datasetId);
  if (!ds) return [];
  return ds.supported_variables
    .map((varId) => CANONICAL_VARIABLES[varId])
    .filter((v): v is CanonicalVariable => v !== undefined);
}
